version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: production
    volumes:
      - webroot:/myapp/public
    env_file:
      .env-prod
    expose:
      - "3000"
    stdin_open: true
    tty: true
  db:
    image: postgres:9.4.1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
    links:
      - db
volumes:
  db-data:
  webroot:
